server:
  port: 8201
spring:
  ## 服务名称
  application:
    name: service_hosp
  ## 环境设置 dev  test  prod
  profiles:
    active: dev
  ## 数据库相关信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  ## 返回JSON时间格式的全局设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl